name: self-harm-triage-notes
channels:
  - conda-forge
dependencies:
  - python=3.12
  - black
  - flake8
  - isort
  - pip
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - scikit-optimize
  - seaborn
  - pyarrow
  - openpyxl
  - pytest
  - pytest-cov
  - spacy
  - pyspellchecker
  - lightgbm
  - pip:
    - python-dotenv
    - -e .
    - krippendorff
    # - scispacy
    - https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_sm-0.5.4.tar.gz
    - -e ../../../ml-health-toolbox